CONSTRUCT {
    ?violation_iri
        a :Violation ;
        :code ?code ;
        :plugin ?plugin .
} WHERE {
    ?violation_file
        a octa:Page ;
        :code ?code ;
        octa:isChildOf+ ?plugin_version .

    ?plugin_version
        a :Flake8PluginVersion ;
        :plugin ?plugin .

    BIND(
        IRI(
            CONCAT(
                "https://flake8.codes/",
                ?code
            )
        )
        AS ?violation_iri
    )
}