INSERT {
    GRAPH <inference> {
        ?violation_file a :BugbearViolation .
    }
} WHERE {
    ?version_directory a :BugbearVersionDirectory .
    ?violation_file octa:isChildOf ?version_directory .

    FILTER NOT EXISTS {
        ?violation_file a octa:IndexPage .
    } .
}
