INSERT {
    GRAPH <local:inference/flake8-bugbear/bugbear-version-index.sparql> {
        ?index_page
            a :BugbearViolationListPage ;
            octa:title ?version .
    }
} WHERE {
    ?version_directory
        a :BugbearVersionDirectory ;
        octa:fileName ?version .

    ?index_page
        octa:isChildOf ?version_directory ;
        a octa:IndexPage .
}
