# List of constants related to a violation.
# Accepts: violation_page - IRI of the violation in question.
SELECT * WHERE {
    ?violation_page
        :relatedConstant ?constant_iri ;
        :version ?version .

    ?constant_page
        :about ?constant_iri ;
        :name ?name ;
        :version ?version ;
        octa:url ?url .
}
