# List of configuration parameters related to a violation.
# Accepts: violation - IRI of the violation in question.
SELECT * WHERE {
    ?violation
        :relatedConfigurationParameter ?parameter ;
        :version ?version .

    ?page
        :about ?parameter ;
        :name ?name ;
        :value ?value ;
        :version ?version ;
        octa:url ?url .
}
