# Expects: ?this_page
SELECT ?code ?title ?url (MAX(?version) as ?latest) WHERE {
    ?this_page :code ?this_code_label .

    ?this_code
        rdfs:label ?this_code_label ;
        :similarTo ?that_code .

    ?that_code
        rdfs:label ?code ;
        octa:subjectOf ?that_page .

    ?that_page
        octa:title ?title ;
        octa:url ?url .
} GROUP BY ?code
