# Expects: ?this_page
SELECT ?code ?title ?url WHERE {
    ?this_page :violation ?this_violation .

    ?this_violation :similarTo ?that_violation .

    ?that_page
        :violation ?that_violation ;
        :code ?code ;
        octa:title ?title ;
        octa:url ?url ;
        :version [
            a :LatestVersion
        ] .
}
