# Given the IRI of category, print all violations in order.
# Expects: ?iri
SELECT * WHERE {
    ?iri octa:isChildOf ?version_directory .

    ?violation
        a :BugbearViolation ;
        :code ?code ;

        octa:isChildOf ?version_directory ;
        octa:title ?title ;
        octa:url ?url .
} ORDER BY ?code
