# Given the IRI of category, print all violations in order.
# Expects: ?iri
SELECT * WHERE {
    ?iri octa:isChildOf ?category_directory .

    ?violation
        a :Violation ;
        :code ?code ;

        octa:isChildOf ?category_directory ;
        octa:title ?title ;
        octa:url ?url .
} ORDER BY ?code
