# Given the IRI of violations directory, print categories in order.
# Expects: ?iri
SELECT * WHERE {
    ?iri octa:isChildOf ?wps_version .

    ?category
        a :WPSViolationsCategoryDirectory ;
        octa:isChildOf+ ?wps_version ;
        octa:isParentOf ?index_page .

    ?index_page
        a octa:IndexPage ;
        octa:title ?title ;
        octa:url ?url .
} ORDER BY ?title
