INSERT {
    GRAPH <local:inference/adr_decisions.sparql> {
        ?choice a :Decision .
    }
} WHERE {
    ?adr :choices ?choice .

    FILTER NOT EXISTS {
         ?adr :excludes ?choice
    } .
}