INSERT {
    GRAPH <local:inference/link_wps_configuration_parameter_to_violation.sparql> {
        ?parameter_page :related-to-violation ?violation_page .
    }
} WHERE {
    ?violation_page :relatedConfigurationParameter ?parameter_python_iri .
    ?parameter_page :about ?parameter_python_iri .
}
