INSERT {
    GRAPH <inference> {
        ?parameter_page :relatedToViolation ?violation_page .
    }
} WHERE {
    ?violation_page :relatedConfigurationParameter ?parameter_python_iri .
    ?parameter_python_iri octa:subjectOf ?parameter_page .
}
