INSERT {
    GRAPH <local:inference/link_wps_constant_to_violation.sparql> {
        ?constant_page :related-to-violation ?violation_page .
    }
} WHERE {
    ?violation_page :relatedConstant ?constant_python_iri .
    ?constant_page :about ?constant_python_iri .
}
