INSERT {
    GRAPH <inference> {
        ?something :related-to-violation ?violation .
    }
} WHERE {
    ?something :related-violation-name ?violation_name .
    ?violation :internalName ?violation_name .
}
